// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cf.proto

/*
Package cf is a generated protocol buffer package.

It is generated from these files:
	cf.proto

It has these top-level messages:
	CfRequest
	CfReply
*/
package cf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CfRequest struct {
	Num1 int64 `protobuf:"varint,1,opt,name=num1" json:"num1,omitempty"`
	Num2 int64 `protobuf:"varint,2,opt,name=num2" json:"num2,omitempty"`
}

func (m *CfRequest) Reset()                    { *m = CfRequest{} }
func (m *CfRequest) String() string            { return proto.CompactTextString(m) }
func (*CfRequest) ProtoMessage()               {}
func (*CfRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CfRequest) GetNum1() int64 {
	if m != nil {
		return m.Num1
	}
	return 0
}

func (m *CfRequest) GetNum2() int64 {
	if m != nil {
		return m.Num2
	}
	return 0
}

type CfReply struct {
	Sum int64 `protobuf:"varint,1,opt,name=sum" json:"sum,omitempty"`
}

func (m *CfReply) Reset()                    { *m = CfReply{} }
func (m *CfReply) String() string            { return proto.CompactTextString(m) }
func (*CfReply) ProtoMessage()               {}
func (*CfReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CfReply) GetSum() int64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*CfRequest)(nil), "cf.CfRequest")
	proto.RegisterType((*CfReply)(nil), "cf.CfReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	Add(ctx context.Context, in *CfRequest, opts ...grpc.CallOption) (*CfReply, error)
	Del(ctx context.Context, in *CfRequest, opts ...grpc.CallOption) (*CfReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Add(ctx context.Context, in *CfRequest, opts ...grpc.CallOption) (*CfReply, error) {
	out := new(CfReply)
	err := grpc.Invoke(ctx, "/cf.Greeter/Add", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Del(ctx context.Context, in *CfRequest, opts ...grpc.CallOption) (*CfReply, error) {
	out := new(CfReply)
	err := grpc.Invoke(ctx, "/cf.Greeter/Del", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	Add(context.Context, *CfRequest) (*CfReply, error)
	Del(context.Context, *CfRequest) (*CfReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cf.Greeter/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Add(ctx, req.(*CfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cf.Greeter/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Del(ctx, req.(*CfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cf.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Greeter_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Greeter_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cf.proto",
}

func init() { proto.RegisterFile("cf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x4e, 0xd3, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4a, 0x4e, 0x53, 0x32, 0xe6, 0xe2, 0x74, 0x4e, 0x0b, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x2b, 0xcd, 0x35, 0x94, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0e, 0x02, 0xb3, 0xa1, 0x62, 0x46, 0x12, 0x4c, 0x70, 0x31, 0x23, 0x25, 0x69,
	0x2e, 0x76, 0x90, 0xa6, 0x82, 0x9c, 0x4a, 0x21, 0x01, 0x2e, 0xe6, 0xe2, 0xd2, 0x5c, 0xa8, 0x0e,
	0x10, 0xd3, 0x28, 0x98, 0x8b, 0xdd, 0xbd, 0x28, 0x35, 0xb5, 0x24, 0xb5, 0x48, 0x48, 0x99, 0x8b,
	0xd9, 0x31, 0x25, 0x45, 0x88, 0x57, 0x2f, 0x39, 0x4d, 0x0f, 0x6e, 0x8b, 0x14, 0x37, 0x8c, 0x5b,
	0x90, 0x53, 0xa9, 0xc4, 0x00, 0x52, 0xe4, 0x92, 0x9a, 0x83, 0x5f, 0x51, 0x12, 0x1b, 0xd8, 0xc5,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xec, 0x89, 0x8c, 0xbd, 0x00, 0x00, 0x00,
}
