# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cf.proto',
  package='cf',
  syntax='proto3',
  serialized_pb=_b('\n\x08\x63\x66.proto\x12\x02\x63\x66\"\'\n\tCfRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x03\x12\x0c\n\x04num2\x18\x02 \x01(\x03\"\x16\n\x07\x43\x66Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x03\x32S\n\x07Greeter\x12#\n\x03\x41\x64\x64\x12\r.cf.CfRequest\x1a\x0b.cf.CfReply\"\x00\x12#\n\x03\x44\x65l\x12\r.cf.CfRequest\x1a\x0b.cf.CfReply\"\x00\x62\x06proto3')
)




_CFREQUEST = _descriptor.Descriptor(
  name='CfRequest',
  full_name='cf.CfRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='cf.CfRequest.num1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num2', full_name='cf.CfRequest.num2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=55,
)


_CFREPLY = _descriptor.Descriptor(
  name='CfReply',
  full_name='cf.CfReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='cf.CfReply.sum', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['CfRequest'] = _CFREQUEST
DESCRIPTOR.message_types_by_name['CfReply'] = _CFREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CfRequest = _reflection.GeneratedProtocolMessageType('CfRequest', (_message.Message,), dict(
  DESCRIPTOR = _CFREQUEST,
  __module__ = 'cf_pb2'
  # @@protoc_insertion_point(class_scope:cf.CfRequest)
  ))
_sym_db.RegisterMessage(CfRequest)

CfReply = _reflection.GeneratedProtocolMessageType('CfReply', (_message.Message,), dict(
  DESCRIPTOR = _CFREPLY,
  __module__ = 'cf_pb2'
  # @@protoc_insertion_point(class_scope:cf.CfReply)
  ))
_sym_db.RegisterMessage(CfReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='cf.Greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=81,
  serialized_end=164,
  methods=[
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='cf.Greeter.Add',
    index=0,
    containing_service=None,
    input_type=_CFREQUEST,
    output_type=_CFREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Del',
    full_name='cf.Greeter.Del',
    index=1,
    containing_service=None,
    input_type=_CFREQUEST,
    output_type=_CFREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
