# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cf_pb2 as cf__pb2


class GreeterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Add = channel.unary_unary(
        '/cf.Greeter/Add',
        request_serializer=cf__pb2.CfRequest.SerializeToString,
        response_deserializer=cf__pb2.CfReply.FromString,
        )
    self.Del = channel.unary_unary(
        '/cf.Greeter/Del',
        request_serializer=cf__pb2.CfRequest.SerializeToString,
        response_deserializer=cf__pb2.CfReply.FromString,
        )


class GreeterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Del(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=cf__pb2.CfRequest.FromString,
          response_serializer=cf__pb2.CfReply.SerializeToString,
      ),
      'Del': grpc.unary_unary_rpc_method_handler(
          servicer.Del,
          request_deserializer=cf__pb2.CfRequest.FromString,
          response_serializer=cf__pb2.CfReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cf.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
